# Spectral examples makefile

CFLAGS = -O2

FFTWOBJS = \
config.o  fcr_9.o fhf_6.o fn_8.o  frc_1.o  ftw_16.o ftwi_7.o \
executor.o fftwnd.o fhf_7.o fn_9.o  frc_10.o ftw_2.o  ftwi_8.o \
fcr_1.o fhb_10.o fhf_8.o fni_1.o frc_11.o ftw_3.o  ftwi_9.o \
fcr_10.o  fhb_16.o fhf_9.o fni_10.o frc_12.o ftw_32.o generic.o \
fcr_11.o  fhb_2.o fn_1.o fni_11.o frc_128.o ftw_4.o  malloc.o \
fcr_12.o  fhb_3.o fn_10.o fni_12.o frc_13.o ftw_5.o  planner.o \
fcr_128.o fhb_32.o fn_11.o fni_13.o frc_14.o ftw_6.o  putils.o \
fcr_13.o  fhb_4.o fn_12.o fni_14.o frc_15.o ftw_64.o rader.o \
fcr_14.o  fhb_5.o fn_13.o fni_15.o frc_16.o ftw_7.o  rconfig.o \
fcr_15.o  fhb_6.o fn_14.o fni_16.o frc_2.o  ftw_8.o  rexec.o \
fcr_16.o  fhb_7.o fn_15.o fni_2.o frc_3.o  ftw_9.o  rexec2.o \
fcr_2.o fhb_8.o fn_16.o fni_3.o frc_32.o ftwi_10.o rfftwf77.o \
fcr_3.o fhb_9.o fn_2.o fni_32.o frc_4.o  ftwi_16.o rfftwnd.o \
fcr_32.o  fhf_10.o fn_3.o fni_4.o frc_5.o  ftwi_2.o rgeneric.o \
fcr_4.o fhf_16.o fn_32.o fni_5.o frc_6.o  ftwi_3.o rplanner.o \
fcr_5.o fhf_2.o fn_4.o fni_6.o frc_64.o ftwi_32.o timer.o \
fcr_6.o fhf_3.o fn_5.o fni_64.o frc_7.o  ftwi_4.o twiddle.o \
fcr_64.o  fhf_32.o fn_6.o fni_7.o frc_8.o  ftwi_5.o wisdom.o \
fcr_7.o fhf_4.o fn_64.o fni_8.o frc_9.o  ftwi_6.o wisdomio.o \
fcr_8.o fhf_5.o fn_7.o fni_9.o ftw_10.o ftwi_64.o 


all: rfftw dft convolution cross ifd pdiff pv pvmorph \
	 simpflt speccomb specreson stft
	 	 
$(FFTWOBJS): %.o: rfftw/%.c 
	$(CC) $(CFLAGS) -c $< -o $@

rfftw: librfft.a $(FFTWOBJS)
    ar 	ar -rcs $@ rfftw/*.o 

dft: 
	$(CC) $(CFLAGS) dft.c -o $@

 